version: '3.8'
services:
  mongo_db:
    container_name: db_container
    image: reemsakr/mongo
    restart: always
    volumes:
    - mongo_db:/data/db

  redis:
    image: redis:6.2-alpine
    container_name: redis_container
    restart: unless-stopped
    expose:
      - 15412

  api:
    build: .
    image: reemsakr/api
    container_name: api_container
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - /app/node_modules  
    environment:
      PORT: 5000
      DB: 'mongodb+srv://reem:123@cluster0.l0ktfho.mongodb.net/gradProject?retryWrites=true&w=majority'
      TOKEN_SECRET: 'my_secret_key'
      appId: '1558016'
      key: '8f885166fac44cd34323'
      secret: '4aba1f8309023e73bc5f'
      cluster: 'mt1' 
      REDIS_URI=: redis-15412.c226.eu-west-1-3.ec2.cloud.redislabs.com'
      REDIS_PASSWORD: 'm3exszZ2CWpD84ZGwX1x1Oh3ZmeXbzUg'
      REDIS_PORT: '15412'
    depends_on:
      - mongo_db  
      - redis
    

volumes:
  mongo_db : {}



